// Auth
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_ERROR_CLEAR = "REGISTER_ERROR_CLEAR";

export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOG_OUT = "LOG_OUT";
export const LOGIN_ERROR_CLEAR = "LOGIN_ERROR_CLEAR";

// Products
export const PRODUCTS_FETCH_START = "PRODUCTS_FETCH_START";
export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
export const PRODUCTS_FETCH_FAIL = "PRODUCTS_FETCH_FAIL";
export const PRODUCTS_SET_CATEGORY = "PRODUCTS_SET_CATEGORY";
export const SET_TOTAL_COUNT = "SET_TOTAL_COUNT"

export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const EDIT_PRODUCT_START = "EDIT_PRODUCT_START";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";
export const SET_NOW_EDITING = "SET_NOT_EDITING";

// Cart
export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

// New Product
export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const OPEN_ADD_PRODUCT_MODAL = "OPEN_ADD_PRODUCT_MODAL";
export const CLOSE_ADD_PRODUCT_MODAL = "CLOSE_ADD_PRODUCT_MODAL";

// BASKET
export const BASKET_ITEMS_GET_START = "BASKET_ITEMS_GET_START";
export const BASKET_ITEMS_GET_SUCCESS = "BASKET_ITEMS_GET_SUCCESS";
export const BASKET_ITEMS_GET_FAIL = "BASKET_ITEMS_GET_SUCCESS";
export const BASKET_ITEM_DELETE_START = 'BASKET_ITEM_DELETE_START'
export const BASKET_ITEM_DELETE_SUCCESS = 'BASKET_ITEM_DELETE_SUCCESS'
export const BASKET_ITEM_DELETE_FAIL = 'BASKET_ITEM_DELETE_FAIL'

// reviews
export const FETCH_REVIEW_START = 'FETCH_REVIEW_START'
export const FETCH_REVIEW_SUCCESS = 'FETCH_REVIEW_SUCCESS'
export const FETCH_REVIEW_FAIL = 'FETCH_REVIEW_FAIL'
export const ADD_REVIEW_START = 'ADD_REVIEW_START'
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS'
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL'
export const UPDATE_REVIEW_START = 'UPDATE_REVIEW_START'
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS'
export const UPDATE_REVIEW_FAIL = 'UPDATE_REVIEW_FAIL'
export const DELETE_REVIEW_START = 'DELETE_REVIEW_START'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'
export const TOGGLE_EDIT_SUCCESS = 'TOGGLE_EDIT_SUCCESS'
export const TOGGLE_EDIT_FAIL = 'TOGGLE_EDIT_FAIL'

// role 
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS'

// admin
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'


export const API_URL = 'http://localhost:3001'