// Auth
export const REGISTER_USER_START = 'REGISTER_USER_START'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'
export const REGISTER_ERROR_CLEAR = 'REGISTER_ERROR_CLEAR';

export const LOGIN_USER_START = 'LOGIN_USER_START'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOG_OUT = 'LOG_OUT'
export const LOGIN_ERROR_CLEAR = 'LOGIN_ERROR_CLEAR';
